In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv("train_FD001.txt", sep="\s+", header=None)
df_test = pd.read_csv("test_FD001.txt", sep="\s+", header=None)
df_rul = pd.read_csv("RUL_FD001.txt", sep="\s+", header=None)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_27992/162218881.py:1: SyntaxWarning: invalid escape sequence '\s'
  df_train = pd.read_csv("train_FD001.txt", sep="\s+", header=None)
/tmp/ipykernel_27992/162218881.py:2: SyntaxWarning: invalid escape sequence '\s'
  df_test = pd.read_csv("test_FD001.txt", sep="\s+", header=None)
/tmp/ipykernel_27992/162218881.py:3: SyntaxWarning: invalid escape sequence '\s'
  df_rul = pd.read_csv("RUL_FD001.txt", sep="\s+", header=None)

In [4]:
column_names = ["unit_number", "time_in_cycles", 
                "op_setting_1", "op_setting_2", "op_setting_3"] + \
               [f"sensor_{i}" for i in range(1, 22)]

df_train.columns = column_names
df_test.columns = column_names
df_rul.columns = ["RUL"]

In [5]:
print(df_train.head())

   unit_number  time_in_cycles  op_setting_1  op_setting_2  op_setting_3  \
0            1               1       -0.0007       -0.0004         100.0
1            1               2        0.0019       -0.0003         100.0
2            1               3       -0.0043        0.0003         100.0
3            1               4        0.0007        0.0000         100.0
4            1               5       -0.0019       -0.0002         100.0

   sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  ...  sensor_12  \
0    518.67    641.82   1589.70   1400.60     14.62  ...     521.66
1    518.67    642.15   1591.82   1403.14     14.62  ...     522.28
2    518.67    642.35   1587.99   1404.20     14.62  ...     522.42
3    518.67    642.35   1582.79   1401.87     14.62  ...     522.86
4    518.67    642.37   1582.85   1406.22     14.62  ...     522.19

   sensor_13  sensor_14  sensor_15  sensor_16  sensor_17  sensor_18  \
0    2388.02    8138.62     8.4195       0.03        392       2388
1    2388.07    8131.49     8.4318       0.03        392       2388
2    2388.03    8133.23     8.4178       0.03        390       2388
3    2388.08    8133.83     8.3682       0.03        392       2388
4    2388.04    8133.80     8.4294       0.03        393       2388

   sensor_19  sensor_20  sensor_21
0      100.0      39.06    23.4190
1      100.0      39.00    23.4236
2      100.0      38.95    23.3442
3      100.0      38.88    23.3739
4      100.0      38.90    23.4044

[5 rows x 26 columns]

In [6]:
print(df_test.head())

   unit_number  time_in_cycles  op_setting_1  op_setting_2  op_setting_3  \
0            1               1        0.0023        0.0003         100.0
1            1               2       -0.0027       -0.0003         100.0
2            1               3        0.0003        0.0001         100.0
3            1               4        0.0042        0.0000         100.0
4            1               5        0.0014        0.0000         100.0

   sensor_1  sensor_2  sensor_3  sensor_4  sensor_5  ...  sensor_12  \
0    518.67    643.02   1585.29   1398.21     14.62  ...     521.72
1    518.67    641.71   1588.45   1395.42     14.62  ...     522.16
2    518.67    642.46   1586.94   1401.34     14.62  ...     521.97
3    518.67    642.44   1584.12   1406.42     14.62  ...     521.38
4    518.67    642.51   1587.19   1401.92     14.62  ...     522.15

   sensor_13  sensor_14  sensor_15  sensor_16  sensor_17  sensor_18  \
0    2388.03    8125.55     8.4052       0.03        392       2388
1    2388.06    8139.62     8.3803       0.03        393       2388
2    2388.03    8130.10     8.4441       0.03        393       2388
3    2388.05    8132.90     8.3917       0.03        391       2388
4    2388.03    8129.54     8.4031       0.03        390       2388

   sensor_19  sensor_20  sensor_21
0      100.0      38.86    23.3735
1      100.0      39.02    23.3916
2      100.0      39.08    23.4166
3      100.0      39.00    23.3737
4      100.0      38.99    23.4130

[5 rows x 26 columns]

In [7]:
print(df_rul.head())

   RUL
0  112
1   98
2   69
3   82
4   91

In [8]:
print("Toplam satır sayısı:", df_train.shape[0])
print("Kaç farklı motor var:", df_train["unit_number"].nunique())

df_train.groupby("unit_number")["time_in_cycles"].max().describe()

Toplam satır sayısı: 20631
Kaç farklı motor var: 100

count    100.000000
mean     206.310000
std       46.342749
min      128.000000
25%      177.000000
50%      199.000000
75%      229.250000
max      362.000000
Name: time_in_cycles, dtype: float64

In [9]:
max_cycles = df_train.groupby("unit_number")["time_in_cycles"].max().reset_index()
max_cycles.columns = ["unit_number", "max_cycle"]

In [10]:
df_train = df_train.merge(max_cycles, on="unit_number", how="left")
df_train["RUL"] = df_train["max_cycle"] - df_train["time_in_cycles"]

In [11]:
df_train[["unit_number", "time_in_cycles", "max_cycle", "RUL"]].head(10)

   unit_number  time_in_cycles  max_cycle  RUL
0            1               1        192  191
1            1               2        192  190
2            1               3        192  189
3            1               4        192  188
4            1               5        192  187
5            1               6        192  186
6            1               7        192  185
7            1               8        192  184
8            1               9        192  183
9            1              10        192  182

In [12]:
df_train[["unit_number", "time_in_cycles", "max_cycle", "RUL"]].tail(10)

       unit_number  time_in_cycles  max_cycle  RUL
20621          100             191        200    9
20622          100             192        200    8
20623          100             193        200    7
20624          100             194        200    6
20625          100             195        200    5
20626          100             196        200    4
20627          100             197        200    3
20628          100             198        200    2
20629          100             199        200    1
20630          100             200        200    0

In [13]:
df_train[[f"sensor_{i}" for i in range(1, 22)]].describe()

,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
count,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,...,20631.000000,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000
mean,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,21.609803,553.367711,2388.096652,9065.242941,1.3,...,521.413470,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705
std,0.00,0.500053,6.131150,9.000605,5.329200e-15,0.001389,0.885092,0.070985,22.082880,0.0,...,0.737553,0.071919,19.076176,0.037505,3.469531e-18,1.548763,0.0,0.0,0.180746,0.108251
min,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,21.600000,549.850000,2387.900000,9021.730000,1.3,...,518.690000,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200
25%,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,21.610000,552.810000,2388.050000,9053.100000,1.3,...,520.960000,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800
50%,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,21.610000,553.440000,2388.090000,9060.660000,1.3,...,521.480000,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900
75%,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,21.610000,554.010000,2388.140000,9069.420000,1.3,...,521.950000,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800
max,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,21.610000,556.060000,2388.560000,9244.590000,1.3,...,523.380000,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400

In [14]:
constant_sensors = ["sensor_1", "sensor_5", "sensor_6", "sensor_10", 
                     "sensor_16", "sensor_18", "sensor_19"]

df_train = df_train.drop(columns=constant_sensors)
df_test = df_test.drop(columns=constant_sensors)

df_train.shape

(20631, 21)